//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishDash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_Items
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> order_date_time { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
