//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishDash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int id { get; set; }
        public Nullable<int> ordered_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
